volumes:
  dev-db-volume: {}
services:
  dev-pg12:
    container_name: rbdip
    hostname: lala4
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: cursa4
      POSTGRESQL_USERNAME: eoeqs
      POSTGRESQL_PASSWORD: eoeqs
    volumes:
      - dev-db-volume:/bitnami/postgresql
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eoeqs"]
      interval: 5s
      timeout: 5s
      retries: 3
  minio:
    container_name: minio-vetcare-rbdip
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: fergoeqs
      MINIO_ROOT_PASSWORD: fergoeqs123456789
    volumes:
      - ./minio-data:/data
    networks:
      - app-network

  minio-setup-2:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set miniovetcare http://minio:9000 fergoeqs fergoeqs123456789;
      mc mb miniovetcare/vetcare || true;
      mc mb miniovetcare/users || true;
      mc mb miniovetcare/pets || true;
      mc anonymous set public miniovetcare/vetcare;
      mc anonymous set public miniovetcare/users;
      mc anonymous set public miniovetcare/pets; 
      echo 'Bucket vetcare-public is now public';
      "
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
