spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cursa4
    username: eoeqs
    password: eoeqs
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
  jpa:
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  jwt:
    secret-key:
    expiration: 360000000000
  mail:
    host: smtp.yandex.ru
    port: 587
    username: stmp@yandex.ru
    password: 111
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.yandex.ru
minio:
  url: http://localhost:9000
  access:
    name: new-access-key
    secret: new-secret-key
    bucket:
      name: vetcare

#logging:
#  level:
#    org:
#      springframework: trace
